language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
git:
  depth: 5
addons:
  firefox: "latest"
script:
  - cd server
  - npm test
before_install:
  - npm i -g npm@latest
install:
  - npm ci
  - gulp build
after_success: npm run coverage