language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
git:
  depth: 5
script:
  - npm test
install:
  - npm ci
before_install:
  - npm i -g npm@latest
after_success: npm run coverage